### ISSUE TITLE
JavaScript Code injection

### ISSUE THREAD

**Issue by stefan2200** [hafiz-ng/Beetlebug#1]
Hey man,

First of all, really nice CTF so far. But I've managed to run into an issue. After finishing the `Load Arbitrary URL` challenge I noticed that the `JavaScript Code Injection` was set to "Done" instead and I'm not sure if my device caused the issue. My flags are the following:

```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <float name="ctf_score_secret_string" value="6.25" />
    <float name="ctf_score_sqlite" value="6.25" />
    <float name="ctf_score_external" value="6.25" />
    <float name="ctf_score_secret_source" value="6.25" />
    <float name="ctf_score_webview" value="6.25" />
    <float name="ctf_score_shared_pref" value="6.25" />
</map>
```

The `ctf_score_xss` is not present and still it shows as "Done" while the `Load Arbitrary URL` is still available:
![image](https://user-images.githubusercontent.com/6204921/164199993-9b59be63-49a3-4c19-9d69-5b42d0de844b.png)

I've temporarily patched the check using frida but it might be something looking into :)

I think the root cause is in `WebViewFragmentHome.java` mixing up the button order:

![image](https://user-images.githubusercontent.com/6204921/164202730-0f16165a-78dc-4fe5-8e9d-5fc6af69979e.png)

**Comment by hafiz-ng** [comment]
Hi Stefan,

I just confirmed the issue. I appreciate bringing it to my attention. I'm currently working on a fix.

Thank you.

**Comment by hafiz-ng** [comment]
The issue has been fixed in the last commit of the main branch. Thanks once again.

**Comment by hafiz-ng** [comment]
The issue has been fixed in the last commit of the main branch. Thanks once again.
